assignment%: assignment%.cc
	g++ -I/usr/share/pythia8/include `root-config --cflags` $@.cc -o $@ -lpythia8 -L/usr/share/pythia8/lib `root-config --glibs`
assignment%%%: assignment%%%.cc
	g++ -I/usr/share/pythia8/include `root-config --cflags` $@.cc -o $@ -lpythia8 -L/usr/share/pythia8/lib `root-config --glibs`
assignment%%%%%%: assignment%%%%%%.cc
	g++ -I/usr/share/pythia8/include `root-config --cflags` $@.cc -o $@ -lpythia8 -L/usr/share/pythia8/lib `root-config --glibs`
assignment%%%%%%%%%%%%%: assignment%%%%%%%%%%%%%.cc
	g++ -I/usr/share/pythia8/include `root-config --cflags` $@.cc -o $@ -lpythia8 -L/usr/share/pythia8/lib `root-config --glibs`
assignment%%%%%%: assignment%%%%%%.cc
	g++ -I/usr/share/pythia8/include `root-config --cflags` $@.cc -o $@ -lpythia8 -L/usr/share/pythia8/lib `root-config --glibs`
plotPDFs: plotPDFs.cc
	g++ -I/usr/include/LHAPDF `root-config --cflags` plotPDFs.cc -o plotPDFs -lLHAPDF `root-config --glibs`
plotPDFs_NN: plotPDFs_NN.cc
	g++ -I/usr/include/LHAPDF `root-config --cflags` plotPDFs_NN.cc -o plotPDFs_NN -lLHAPDF `root-config --glibs`
plotPDFs_NNN: plotPDFs_NNN.cc
	g++ -I/usr/include/LHAPDF `root-config --cflags` plotPDFs_NNN.cc -o plotPDFs_NN -lLHAPDF `root-config --glibs`
